name:                unify
version:             0.0.1.1
github:              "owestphal/unify"
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "o_westphal (at) online (dot) de"
copyright:           "2020 Oliver Westphal"

# Metadata used when publishing your package
category:            Unification

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/owestphal/unify#readme>

dependencies:
- base >= 4.8 && < 5
- transformers
- containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fdefer-typed-holes
  exposed-modules:
  - Unify
  - Match

tests:
  unify-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unify
    - hspec
